data:
  root: "./datasets/LOL/"
  train_dir: "train"
  test_dir: "test"
  input_dir: "low"
  target_dir: "light"  
  image_size: 256
  batch_size: 4
  num_workers: 4
  max_len: 1  

model:
  num_blocks: [2, 3, 3, 4]
  num_heads: [1, 2, 4, 8]
  channels: [16, 32, 64, 128]
  num_refinement: 4
  expansion_factor: 2.66
  ch: [16, 16, 32, 64]
  loss_weights:
    charbonnier: 3.0
    perceptual: 0.2
    smoothness: 0.02
    exposure: 0.1
    noise_aware: 0.05
    edge: 0.5
  

training:
  model_dir: "./outputs/LOL/"
  epochs: 800
  batch_size: 4
  learning_rate: 1e-3
  weight_decay: 2e-5
  warmup_epochs: 10
  save_freq: 10
  eval_freq: 5
  print_freq: 100
  
  optimization:
    optimizer:
      name: "AdamW"
      lr: 0.0003
      weight_decay: 0.0001
      betas: [0.9, 0.999]
    
    scheduler:
      name: "CosineAnnealingLR"
      T_max: 800
      eta_min: 0.00001

evaluation:
  metrics: ["psnr", "ssim", "lpips"]
  save_images: true
  save_high_res: false 