data:
  root: "./datasets/LOL/"
  train_dir: "train"
  test_dir: "test"
  input_dir: "low"
  target_dir: "light"  
  image_size: 256
  max_len: 1  

model:
  num_blocks: [2, 3, 3, 4]
  num_heads: [1, 2, 4, 8]
  channels: [16, 32, 64, 128]
  num_refinement: 4
  expansion_factor: 2.66
  ch: [16, 16, 32, 64]
  loss:
    charbonnier: 2.0  
    perceptual: 0.2  
    ssim: 0.1
    grad: 0.2         

training:
  model_dir: "./outputs_LOLv2"
  learning_rate: 0.0001
  weight_decay: 2e-5
  warmup_epochs: 0
  print_freq: 100
  
  optimization:
    optimizer:
      name: "AdamW"
      lr: 0.0001
      weight_decay: 0.0001
      betas: [0.9, 0.999]
    
    scheduler:
      name: "CosineAnnealingLR"
      T_max: 2000  # align with planned epochs if stepping per-epoch
      eta_min: 0.00001

evaluation:
  metrics: ["psnr", "ssim", "lpips"]
  save_images: true
  save_high_res: false 